on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.5.0